---
- hosts: tmaxlinux
  #gather_facts: no
  tasks:
    - name: Find OS version
      shell: "cat /etc/issue.net"
      register: os_version

    - name: Find my home
      shell: "grep '{{ ansible_user }}:' /etc/passwd | awk -F: '{ print $6 }' | head -1"
      register: user_home

    - name: Make the temp directory
      file:
        path: '{{ user_home.stdout }}/sc_tmp'
        state: directory
        mode: 0755

    - name: Construct the package list (Installed)
      #shell: apt list --installed > /test.txt
      #shell: apt list --installed | cut -d '/' -f1 > /test.txt
      shell: apt list --installed | cut -d '/' -f1  | sed '1d' | tee '{{ user_home.stdout }}/sc_tmp/pkg_list_ins.txt'
      #shell: apt list --installed | cut -d '/' -f1  | sed '1d' > '{{ user_home.stdout }}/sc_tmp/pkg_list_ins.txt'
      register: pkg_name
      when: os_version.stdout.find('Ubuntu 17.10') != -1 or os_version.stdout.find('TmaxLinux 4.0') != -1      
      become: true

    - name: Debug message
      debug:
        msg: "{{ pkg_name.stdout.split('\n')[0] }}"

    - name: Generate the package description
      shell: apt show nginx > '{{ user_home.stdout }}/sc_tmp/nginx.txt'
      #shell: apt show '{{ pkg_name.stdout[0] }}' > '{{ user_home.stdout }}/sc_tmp/{{ pkg_name.stdout }}.txt'
    
    - name: Fetch the package details
      fetch:
        src: '{{ user_home.stdout }}/sc_tmp/nginx.txt'
        dest: '{{ PATH_SC_PKG_LIST }}/{{ GROUP_NAME }}/{{ inventory_hostname }}/'
        flat: yes

    - name: Delete the package list in remote node
      #command: "rm -rf /test.txt"
      file:
        dest: '{{ user_home.stdout }}/sc_tmp/nginx.txt'
        state: absent
      become: true
