---
- hosts: tmaxlinux
  #gather_facts: no
  tasks:
    - name: Find OS version
      shell: "cat /etc/issue.net"
      register: os_version

    - name: Find my home
      shell: "grep '{{ ansible_user }}:' /etc/passwd | awk -F: '{ print $6 }' | head -1"
      register: user_home

    - name: Make the temp directory
      file:
        path: '{{ user_home.stdout }}/sc_tmp'
        state: directory
        mode: 0755

    - name: Construct the package list (To-be Upgrade)
      shell: apt-get upgrade --just-print > '{{ user_home.stdout }}/sc_tmp/pkg_list_upg_pre.txt'
      when: os_version.stdout.find('Ubuntu 17.10') != -1 or os_version.stdout.find('TmaxLinux 4.0') != -1      
      become: true

    - name: Push the shell script for parsing
      copy:
        src: ../files/parsing.sh
        dest: '{{ user_home.stdout }}/sc_tmp/'
        mode: 0755

    - name: Perform the shell script
      shell: "{{ user_home.stdout }}/sc_tmp/parsing.sh > {{ user_home.stdout }}/sc_tmp/pkg_list_upg.txt"
      args:
        chdir: '{{ user_home.stdout }}/sc_tmp/'
      become: true
      
    - name: Fetch the package list
      fetch:
        src: '{{ user_home.stdout }}/sc_tmp/pkg_list_upg.txt'
        dest: '/home/po7/SC_PKG_LIST/{{ inventory_hostname }}/'
        flat: yes

    - name: Delete the package list in remote node
      #command: "rm -rf /test.txt"
      file:
        dest: '{{ user_home.stdout }}/sc_tmp/pkg_list_upg.txt'
        state: absent
      become: true
