---
- hosts: tmaxlinux
  tasks:
    - name: Find OS version
      shell: "cat /etc/issue.net"
      register: os_version

    #- name: Grep the pakcage name
    #  shell: "cat /etc/pkgname"
    #  register: pkg_name

    - name: Upgrade the package on the remote node
      apt:
        name: '{{ packName }}'
        state: latest
        update_cache: yes
      when: os_version.stdout.find('Ubuntu 17.10') != -1 or os_version.stdout.find('TmaxLinux 4.0') != -1
      become: true
      #when: ansible_distribution == "Ubuntu" | ansible_distribution == "TmaxLinux"
      #with_itmes:
