---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Find OS version
      shell: "cat /etc/issue.net"
      register: os_version

    - name: Find my home
      shell: "grep '{{ ansible_user }}:' /etc/passwd | awk -F: '{ print $6 }' | head -1"
      register: user_home

    - name: Make the temp directory
      file:
        path: '{{ user_home.stdout }}/sc_tmp'
        state: directory
        mode: 0755

    - name: Verify the package by setting the key
      shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9011567A260F6FE7
      become: true
    
    - name: Construct the package list (in repository)
      shell: apt list | cut -d '/' -f1  | sed '1d' > '{{ user_home.stdout }}/sc_tmp/pkg_list_rep.txt'
      become: true

    - name: Fetch the package list
      fetch:
        src: '{{ user_home.stdout }}/sc_tmp/pkg_list_rep.txt'
        dest: '{{ PATH_SC_PKG_LIST }}/{{ GROUP_NAME }}/{{ inventory_hostname }}/'
        flat: yes

    - name: Delete the package list in remote node
      file:
        dest: '{{ user_home.stdout }}/sc_tmp/pkg_list_rep.txt'
        state: absent
      become: true
