---
- hosts: '{{ GROUP_NAME }}'
  vars_files:
    - "../../vars/common_vars.yml"
  tasks:
    - name: Find OS version
      shell: "cat /etc/issue.net"
      register: os_version

    - name: Find my home
      shell: "grep '{{ ansible_user }}:' /etc/passwd | awk -F: '{ print $6 }' | head -1"
      register: user_home

    - name: Make the temp directory
      file:
        path: '{{ user_home.stdout }}/sc_tmp'
        state: directory
        mode: 0755

    - name: Copy the package list (to be installed)
      copy:
        src: '{{ PATH_SC_PKG_LIST }}/{{ GROUP_NAME }}/{{ inventory_hostname }}/add.json'
        dest: '{{ user_home.stdout }}/sc_tmp/add.json'

    - name: Register package variable
      shell: "cat {{ user_home.stdout }}/sc_tmp/add.json"
      register: packName

    - name: Install the package on the remote node
      apt:
        name: "{{ packName.stdout.split('\n') }}"
        state: present
        update_cache: yes
      become: true
      when: os_version.stdout.find('Ubuntu 17.10') != -1 or os_version.stdout.find('TmaxLinux 4.0') != -1
