---
- hosts: '{{ GROUP_NAME }}'
  vars_files:
    - "../../vars/common_vars.yml"
  tasks:
    - name: Find OS version
      shell: "cat /etc/issue.net"
      register: os_version

    - name: Upgrade the package on the remote node
      apt:
        name: '{{ packName }}'
        state: latest
        update_cache: yes
      when: os_version.stdout.find('Ubuntu 17.10') != -1 or os_version.stdout.find('TmaxLinux 4.0') != -1
      become: true
