---
- hosts: '{{ GROUP_NAME }}'
  vars_files:
    - "../../vars/common_vars.yml"
  tasks:
    - name: Find OS version
      shell: "cat /etc/issue.net"
      register: os_version

    - name: Delete the SSH Port
      shell: sed -e 's/Port {{ del_port }}//g' /etc/ssh/sshd_config > /etc/ssh/sshd_config_tmp
      become: true

    - name: Copy the SSH Config
      shell: mv /etc/ssh/sshd_config_tmp /etc/ssh/sshd_config
      become: true

    - name: Restart SSH Daemon
      shell: service sshd restart
      become: true

    - name: Check the UFW status
      shell: ufw status verbose
      register: ufw_status
      become: true

    - name: Deny the Port (Ubuntu Firewall)
      shell: 'ufw deny {{ del_port }}'
      when: ufw_status.stdout.find('inactive') == -1
      become: true
